---
name: cf-mjs-paas

director_uuid: 4048d97d-f435-495a-9a70-33ca4dcd7e0e 

meta:
  environment: env
  
  openstack:
    net_id: 0757784c-6f3a-49e1-8a4a-91c9b3fcb665
    auth_url: http://14.63.202.11:5000/v2.0/tokens
    tenant: pivotal
    username: pivotal
    api_key: pivotalpaas
    security_groups: [opsmanager]
    
  floating_static_ips:
  - 14.63.202.120

compilation:
  cloud_properties:
    instance_type: m1.medium
  network: cf1
  reuse_compilation_vms: false
  workers: 6

networks:
  - name: floating
    type: vip
    cloud_properties:
      net_id: be892b39-5b37-4c7d-82bc-23510e336a91
      security_groups: [opsmanager]

  - name: cf1
    type: manual
    subnets:
    - range: 10.10.5.0/24
      gateway: 10.10.5.1
      reserved:
      - 10.10.5.2 - 10.10.5.10
      - 10.10.5.250 - 10.10.5.254
      dns:
      - 192.168.0.175
      - 8.8.8.8
      static:
      - 10.10.5.11 - 10.10.5.50
      cloud_properties:
        net_id: 318d18f1-7891-4b9b-8bcb-4a6ac0060fd8
        security_groups: 
        - opsmanager
        
  - name: cf2
    type: manual
    subnets:
    - range: 10.10.6.0/24
      gateway: 10.10.6.1
      reserved:
      - 10.10.6.240 - 10.10.6.254
      dns:
      - 192.168.0.175
      - 8.8.8.8
      static:
      - 10.10.6.2 - 10.10.6.30
      cloud_properties:
        net_id: 0757784c-6f3a-49e1-8a4a-91c9b3fcb665        
        security_groups: 
        - opsmanager  

properties:
  domain: ktds.cloud.com
  system_domain: system.ktds.cloud.com
  system_domain_organization: system_org
  app_domains:
   - ktds.cloud.com

  ssl:
    skip_cert_verify: true

  cc:
    staging_upload_user: STAGING_UPLOAD_USER
    staging_upload_password: STAGING_UPLOAD_PASSWORD
    bulk_api_password: BULK_API_PASSWORD
    db_encryption_key: DB_ENCRYPTION_KEY
    uaa_skip_ssl_validation: true
    
    default_quota_definition: default
    quota_definitions:
      default:
        memory_limit: 10240
        total_services: 100
        total_routes: 1000
        non_basic_services_allowed: true
      free:
        memory_limit: 0
        total_services: 10
        total_routes: 1000
        non_basic_services_allowed: false
      paid:
        memory_limit: 10240
        total_services: -1
        total_routes: 1000
        non_basic_services_allowed: true
      runaway:
        memory_limit: 153600
        total_services: -1
        total_routes: 1000
        non_basic_services_allowed: true
      trial:
        non_basic_services_allowed: false
        total_services: 10
        memory_limit: 2048
        total_routes: 1000
        trial_db_allowed: true
    
  blobstore:
    admin_users:
      - username: blobstore-username
        password: blobstore-password
    secure_link:
      secret: blobstore-secret
    tls:
      port: 443
      cert: |+
        -----BEGIN CERTIFICATE-----
        MIIDmDCCAoACCQD8mbiHIO6CkDANBgkqhkiG9w0BAQsFADCBjDELMAkGA1UEBhMC
        S1IxDjAMBgNVBAgMBVNlb3VsMRAwDgYDVQQHDAdtb2tkb25nMQ0wCwYDVQQKDARr
        dGRzMQ4wDAYDVQQLDAVjbG91ZDEZMBcGA1UEAwwQKi5rdGRzLmNsb3VkLmNvbTEh
        MB8GCSqGSIb3DQEJARYSamluLXN1Lm1vb25Aa3QuY29tMCAXDTE1MTAyOTA1MTcy
        MVoYDzIxMTUxMDA1MDUxNzIxWjCBjDELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNl
        b3VsMRAwDgYDVQQHDAdtb2tkb25nMQ0wCwYDVQQKDARrdGRzMQ4wDAYDVQQLDAVj
        bG91ZDEZMBcGA1UEAwwQKi5rdGRzLmNsb3VkLmNvbTEhMB8GCSqGSIb3DQEJARYS
        amluLXN1Lm1vb25Aa3QuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
        AQEA1nQP/VQ8yZAVmu4wCaQFwfi9grYAmmb/1Uj6fQXd2w4AKorUJE9OU7HpFUec
        NGBhuyhKPAnrOU71uifXE0pRgAzkjkDu1aTekH4jyRdfCqLQL7htRs87I6YH/bmZ
        EU2Q+Sdus1WWdwCgYG11dnjmCbG/0LGl36x0IxCA+iDwQbQ8eKE15iq3do0JB8Vf
        zxdjpVS1LxYHVd1TeT/rndF2iGNhUtxEi/lutOifmuqMotANrhjN0EZEu4kDiREp
        C3jYXxuOpSze1SXlQ+Q8Kz9MGfBOqcNyo1tMCTuOCtnE9gz6F9tjndiwf1P5vTw/
        6ghZ0GM6dMktZ3DkZo6Rqo/U+QIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQDSaeE/
        4pdTGCLQHvtODDlJuOd/z2d+jStHB4RR2iNgS9dhzaPzrg3+DeMkNFj+pwNmcBn5
        pvtaYn37lAjfm0jA72T0z1u1+i24xKuXnBM5/eN5g94ZuRCdXiwpJXtDai/LJRox
        0Zw3jBvdiwZqo9pKjraySQdcSNiaIxRkZFefIezGw4LQ9mROkuGVQCVlVATVDNwr
        C4uVkdl/Csl1VSbE6jKiSl/Hg6JgtJnEK+Z+cyVQZH+iaU1UI6hGo6VMsYCB5ObP
        9JM4UbUTVIDWPXgq8k+29avGpWlvIoWlp5xI/m/NPTZXjj9JuqM7mw0yX6PkLMQp
        spNcm1KYtyXOmWvV
        -----END CERTIFICATE-----
      private_key: |+
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEA1nQP/VQ8yZAVmu4wCaQFwfi9grYAmmb/1Uj6fQXd2w4AKorU
        JE9OU7HpFUecNGBhuyhKPAnrOU71uifXE0pRgAzkjkDu1aTekH4jyRdfCqLQL7ht
        Rs87I6YH/bmZEU2Q+Sdus1WWdwCgYG11dnjmCbG/0LGl36x0IxCA+iDwQbQ8eKE1
        5iq3do0JB8VfzxdjpVS1LxYHVd1TeT/rndF2iGNhUtxEi/lutOifmuqMotANrhjN
        0EZEu4kDiREpC3jYXxuOpSze1SXlQ+Q8Kz9MGfBOqcNyo1tMCTuOCtnE9gz6F9tj
        ndiwf1P5vTw/6ghZ0GM6dMktZ3DkZo6Rqo/U+QIDAQABAoIBAET0wuNxP66MPvY3
        WojvDc7mPYGXJjB/qAmb0rd6uHCkWtdTFo2qVoRA87Kc+RQ6XZKBjQUrJ1ChHBBE
        mTqhrf0fqCo5pNJblhkeBkG12yCfY5PEmJapMdnvnCgwkpBmwZPr4wOVJLGVKPx4
        lcmHbGh3mDbxuGVonVtdBivnhXmKdKTsodtSIcWkaCFU4/3+FJQzgkPGgXaxdhIv
        Eqvd+DaCHnAMxk206o5BEdIl0X18cN3GTS1R901mMl+dzv/PBNtSiZ0rstdek1ma
        XwPE+Zo/vDWWBDnU2989PFJqaV8AzOrN46moByHG07frc2GsF6D2CYCJLDbBHC+x
        Aak8MpECgYEA/szekTbNXzfZ6VxzUoyC4f3asfa74+mimzBLqeMzsxgr2+Vwz6/P
        rAIwbjYD9rno+xGHwjA9wuId14ZuaTQKIhHePhMlGK9amohahEPeYNwohB9uskUO
        bYvCsjZwybhe9V409W9ct2HDmo24Bro27iXBudxblJQeMxci7zwNQaUCgYEA13aP
        TrZi7oibgqHLyRLJu67WXrq62QAM1ruYavLd9Cvay1ap25RptKoyLC4ORz8FuwhC
        PYXHdTwnTWuVDQMIRR/fh/IYS6TV3UM2hQmTdpdVTO+MKXC9guEGksY/m2kYc0E2
        +gmnkEdLLnlma4ou35WeU3Uth7i9HKqs/N9YPcUCgYEAymk5TaZ5U3Ds3SMiQat5
        tcmR19onvJA3Ko0dLmJdCaLkBJWqHnKNyRkcHBEw6OkbGYf9jtf/2DcEedhDEbPT
        cOk84ZcX2xpCIYy8S2IW4F9EmGDX8SpGoeNq0WPKCZU7ajRiYa8Lumohlz+Jt15q
        kJjR4rIY1lkr/G4exGmyJjkCgYEAy8/JpZJfKPYt7DbyVsSf8Rpki30lC+nBO0p+
        1gPgsnzdXWUgDaZpC03HYgU62mgiGpaoWhv23c3F+7UdbA6HPyP0RVtbYgqNhtxy
        cQvq4s4qETmzouuTSH9lwWcoefDDARsaTxDc4VyfIFoT6PvwdOzJtHZuWCkHMlu8
        gQMgLGUCgYAnXdI7V6yagCdnBfZjn0i5943OG9PrrLumnynre6HHf4RcyGioiGqg
        YHBxaxlChEts6H6RcQ0Q5yVFoCVtg4lZzb7mzhTf3Q/OuIVbjib40lfwDHIBMA7T
        AOfWY90ipsDk2xGkwuJwPmDaE8rHxYWMJJDWR0eBUqcGGfl9Jn5A0w==
        -----END RSA PRIVATE KEY-----
  consul:
    encrypt_keys:
      - CONSUL_ENCRYPT_KEY
    ca_cert: CONSUL_CA_CERT
    server_cert: CONSUL_SERVER_CERT
    server_key: CONSUL_SERVER_KEY
    agent_cert: CONSUL_AGENT_CERT
    agent_key: CONSUL_AGENT_KEY
    require_ssl: false
    
  dea_next:
    disk_mb: 10240
    memory_mb: 4096
    
  loggregator_endpoint:
    shared_secret: LOGGREGATOR_ENDPOINT_SHARED_SECRET
    
  login:
    protocol: null
    
  nats:
    user: nats
    password: nats
    
  router:
    status:
      user: ROUTER_USER
      password: ROUTER_PASSWORD
      
  uaa:
    admin:
      client_secret: ADMIN_SECRET
    cc:
      client_secret: CC_CLIENT_SECRET
    clients:
      cc_routing:
        secret: CC_ROUTING_SECRET
      cloud_controller_username_lookup:
        secret: CLOUD_CONTROLLER_USERNAME_LOOKUP_SECRET
      doppler:
        secret: DOPPLER_SECRET
      gorouter:
        secret: GOROUTER_SECRET
      tcp_emitter:
        secret: TCP-EMITTER-SECRET
      tcp_router:
        secret: TCP-ROUTER-SECRET
      login:
        secret: LOGIN_CLIENT_SECRET
      notifications:
        secret: NOTIFICATIONS_CLIENT_SECRET
    jwt:
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----

    scim:
      users:
        - admin|admin|scim.write,scim.read,openid,cloud_controller.admin,doppler.firehose

  ccdb:
    roles:
    - name: ccadmin
      password: CCDB_PASSWORD
      
  uaadb:
    roles:
    - name: uaaadmin
      password: UAADB_PASSWORD
      
  databases:
    roles:
    - name: ccadmin
      password: CCDB_PASSWORD
    - name: uaaadmin
      password: UAADB_PASSWORD

jobs:
  - name: ha_proxy_z1
    networks:
      - name: cf1
        default:
        - dns
        - gateway
    properties:
      ha_proxy:
        ssl_pem: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEA1nQP/VQ8yZAVmu4wCaQFwfi9grYAmmb/1Uj6fQXd2w4AKorU
          JE9OU7HpFUecNGBhuyhKPAnrOU71uifXE0pRgAzkjkDu1aTekH4jyRdfCqLQL7ht
          Rs87I6YH/bmZEU2Q+Sdus1WWdwCgYG11dnjmCbG/0LGl36x0IxCA+iDwQbQ8eKE1
          5iq3do0JB8VfzxdjpVS1LxYHVd1TeT/rndF2iGNhUtxEi/lutOifmuqMotANrhjN
          0EZEu4kDiREpC3jYXxuOpSze1SXlQ+Q8Kz9MGfBOqcNyo1tMCTuOCtnE9gz6F9tj
          ndiwf1P5vTw/6ghZ0GM6dMktZ3DkZo6Rqo/U+QIDAQABAoIBAET0wuNxP66MPvY3
          WojvDc7mPYGXJjB/qAmb0rd6uHCkWtdTFo2qVoRA87Kc+RQ6XZKBjQUrJ1ChHBBE
          mTqhrf0fqCo5pNJblhkeBkG12yCfY5PEmJapMdnvnCgwkpBmwZPr4wOVJLGVKPx4
          lcmHbGh3mDbxuGVonVtdBivnhXmKdKTsodtSIcWkaCFU4/3+FJQzgkPGgXaxdhIv
          Eqvd+DaCHnAMxk206o5BEdIl0X18cN3GTS1R901mMl+dzv/PBNtSiZ0rstdek1ma
          XwPE+Zo/vDWWBDnU2989PFJqaV8AzOrN46moByHG07frc2GsF6D2CYCJLDbBHC+x
          Aak8MpECgYEA/szekTbNXzfZ6VxzUoyC4f3asfa74+mimzBLqeMzsxgr2+Vwz6/P
          rAIwbjYD9rno+xGHwjA9wuId14ZuaTQKIhHePhMlGK9amohahEPeYNwohB9uskUO
          bYvCsjZwybhe9V409W9ct2HDmo24Bro27iXBudxblJQeMxci7zwNQaUCgYEA13aP
          TrZi7oibgqHLyRLJu67WXrq62QAM1ruYavLd9Cvay1ap25RptKoyLC4ORz8FuwhC
          PYXHdTwnTWuVDQMIRR/fh/IYS6TV3UM2hQmTdpdVTO+MKXC9guEGksY/m2kYc0E2
          +gmnkEdLLnlma4ou35WeU3Uth7i9HKqs/N9YPcUCgYEAymk5TaZ5U3Ds3SMiQat5
          tcmR19onvJA3Ko0dLmJdCaLkBJWqHnKNyRkcHBEw6OkbGYf9jtf/2DcEedhDEbPT
          cOk84ZcX2xpCIYy8S2IW4F9EmGDX8SpGoeNq0WPKCZU7ajRiYa8Lumohlz+Jt15q
          kJjR4rIY1lkr/G4exGmyJjkCgYEAy8/JpZJfKPYt7DbyVsSf8Rpki30lC+nBO0p+
          1gPgsnzdXWUgDaZpC03HYgU62mgiGpaoWhv23c3F+7UdbA6HPyP0RVtbYgqNhtxy
          cQvq4s4qETmzouuTSH9lwWcoefDDARsaTxDc4VyfIFoT6PvwdOzJtHZuWCkHMlu8
          gQMgLGUCgYAnXdI7V6yagCdnBfZjn0i5943OG9PrrLumnynre6HHf4RcyGioiGqg
          YHBxaxlChEts6H6RcQ0Q5yVFoCVtg4lZzb7mzhTf3Q/OuIVbjib40lfwDHIBMA7T
          AOfWY90ipsDk2xGkwuJwPmDaE8rHxYWMJJDWR0eBUqcGGfl9Jn5A0w==
          -----END RSA PRIVATE KEY-----
          -----BEGIN CERTIFICATE-----
          MIIDmDCCAoACCQD8mbiHIO6CkDANBgkqhkiG9w0BAQsFADCBjDELMAkGA1UEBhMC
          S1IxDjAMBgNVBAgMBVNlb3VsMRAwDgYDVQQHDAdtb2tkb25nMQ0wCwYDVQQKDARr
          dGRzMQ4wDAYDVQQLDAVjbG91ZDEZMBcGA1UEAwwQKi5rdGRzLmNsb3VkLmNvbTEh
          MB8GCSqGSIb3DQEJARYSamluLXN1Lm1vb25Aa3QuY29tMCAXDTE1MTAyOTA1MTcy
          MVoYDzIxMTUxMDA1MDUxNzIxWjCBjDELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNl
          b3VsMRAwDgYDVQQHDAdtb2tkb25nMQ0wCwYDVQQKDARrdGRzMQ4wDAYDVQQLDAVj
          bG91ZDEZMBcGA1UEAwwQKi5rdGRzLmNsb3VkLmNvbTEhMB8GCSqGSIb3DQEJARYS
          amluLXN1Lm1vb25Aa3QuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
          AQEA1nQP/VQ8yZAVmu4wCaQFwfi9grYAmmb/1Uj6fQXd2w4AKorUJE9OU7HpFUec
          NGBhuyhKPAnrOU71uifXE0pRgAzkjkDu1aTekH4jyRdfCqLQL7htRs87I6YH/bmZ
          EU2Q+Sdus1WWdwCgYG11dnjmCbG/0LGl36x0IxCA+iDwQbQ8eKE15iq3do0JB8Vf
          zxdjpVS1LxYHVd1TeT/rndF2iGNhUtxEi/lutOifmuqMotANrhjN0EZEu4kDiREp
          C3jYXxuOpSze1SXlQ+Q8Kz9MGfBOqcNyo1tMCTuOCtnE9gz6F9tjndiwf1P5vTw/
          6ghZ0GM6dMktZ3DkZo6Rqo/U+QIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQDSaeE/
          4pdTGCLQHvtODDlJuOd/z2d+jStHB4RR2iNgS9dhzaPzrg3+DeMkNFj+pwNmcBn5
          pvtaYn37lAjfm0jA72T0z1u1+i24xKuXnBM5/eN5g94ZuRCdXiwpJXtDai/LJRox
          0Zw3jBvdiwZqo9pKjraySQdcSNiaIxRkZFefIezGw4LQ9mROkuGVQCVlVATVDNwr
          C4uVkdl/Csl1VSbE6jKiSl/Hg6JgtJnEK+Z+cyVQZH+iaU1UI6hGo6VMsYCB5ObP
          9JM4UbUTVIDWPXgq8k+29avGpWlvIoWlp5xI/m/NPTZXjj9JuqM7mw0yX6PkLMQp
          spNcm1KYtyXOmWvV
          -----END CERTIFICATE-----
#  - name: api_z1
#    instances: 1
#
#  - name: api_worker_z1
#    instances: 0
#  - name: clock_global
#    instances: 0
  - name: runner_z1
    instances: 3
#  - name: etcd_z1
#    instances: 1
#  - name: nats_z1
#   instances: 1
#  - name: router_z1
#    instances: 1
